import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  HeadingLevel,
  ImageRun,
  Packer,
  PageNumber,
  Paragraph,
  TextRun,
} from "docx";
import { sanitizeEditorialText } from "@/lib/phrenos-updates/sanitize";

const FONT = "Arial";
const BRAND_GREEN = "1F3A2B";
const GREY = "7F7F7F";
const LOGO_PATH = "/brand/phrenos_logo_green.png";
// The logo file is 352 x 368; it is shown at this size in the page header.
const LOGO_WIDTH = 44;
const LOGO_HEIGHT = 46;
const BRAND_SITE = "phrenosai.com";

export type DraftForWord = {
  suggestion_type: string;
  title: string;
  hook: string;
  body_html: string;
  cta: string;
  hashtags: string;
  image_ideas: string;
};

const plain = (text: string) => sanitizeEditorialText(text);

/** Paragraph breaks kept, tags removed, for turning draft HTML into Word paragraphs. */
function htmlToParagraphText(html: string): string {
  return html
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/[ \t]+/g, " ")
    .replace(/ *\n */g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/** Headings, paragraphs, quotes and lists from the draft's HTML, in order. */
function bodyToParagraphs(html: string, fillLink: (text: string) => string): Paragraph[] {
  const blocks: Paragraph[] = [];
  const pattern = /<(h[2-4]|p|blockquote|ul|ol)\b[^>]*>([\s\S]*?)<\/\1>/gi;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(html)) !== null) {
    const tag = match[1].toLowerCase();
    if (tag === "ul" || tag === "ol") {
      const items = match[2].match(/<li\b[^>]*>[\s\S]*?<\/li>/gi) ?? [];
      for (const item of items) {
        const text = fillLink(htmlToParagraphText(item));
        if (text) blocks.push(new Paragraph({ text, bullet: { level: 0 }, spacing: { after: 80 } }));
      }
      continue;
    }
    const text = fillLink(htmlToParagraphText(match[2]));
    if (!text) continue;
    if (tag.startsWith("h")) {
      blocks.push(new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 } }));
    } else if (tag === "blockquote") {
      blocks.push(new Paragraph({ children: [new TextRun({ text, italics: true })], indent: { left: 400 }, spacing: { after: 120 } }));
    } else {
      blocks.push(new Paragraph({ text, spacing: { after: 140 } }));
    }
  }
  if (blocks.length === 0) {
    for (const paragraph of fillLink(htmlToParagraphText(html)).split(/\n{2,}/).filter(Boolean)) {
      blocks.push(new Paragraph({ text: paragraph, spacing: { after: 140 } }));
    }
  }
  return blocks;
}

/** The logo at the top of every page, and a "generated by" line with the date at the bottom. */
function brandedHeaderFooter(documentLabel: string, logo: Uint8Array | null) {
  const generatedOn = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "Europe/London",
  });
  return {
    headers: {
      default: new Header({
        children: [
          new Paragraph({
            spacing: { after: 120 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "BFBFBF", space: 6 } },
            children: [
              ...(logo
                ? [new ImageRun({ type: "png", data: logo, transformation: { width: LOGO_WIDTH, height: LOGO_HEIGHT } })]
                : []),
              new TextRun({ text: "   Phrenos.ai", bold: true, font: FONT, size: 22, color: BRAND_GREEN }),
            ],
          }),
        ],
      }),
    },
    footers: {
      default: new Footer({
        children: [
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: `Generated by Phrenos.ai (${BRAND_SITE}) on ${generatedOn}`, font: FONT, size: 16, color: GREY })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: `${documentLabel}   |   Page `, font: FONT, size: 16, color: GREY }),
              new TextRun({ children: [PageNumber.CURRENT], font: FONT, size: 16, color: GREY }),
            ],
          }),
        ],
      }),
    },
  };
}

/** A single blog draft laid out for Word, with the Phrenos.ai logo in the header. */
export function buildDraftDocument(
  draft: DraftForWord,
  isFullDraft: boolean,
  logo: Uint8Array | null,
) {
  const fillLink = (text: string) => plain(text);
  const children: Paragraph[] = [
    new Paragraph({
      children: [new TextRun({ text: `Blog, ${isFullDraft ? "featured draft" : "idea"}`, color: GREY, size: 20 })],
      spacing: { after: 80 },
    }),
    new Paragraph({ text: plain(draft.title), heading: HeadingLevel.TITLE, spacing: { after: 200 } }),
  ];

  if (draft.hook) {
    children.push(
      new Paragraph({ children: [new TextRun({ text: fillLink(draft.hook), bold: true, italics: true })], spacing: { after: 180 } }),
    );
  }
  children.push(...bodyToParagraphs(draft.body_html, fillLink));

  if (draft.cta) {
    // The CTA keeps its paragraph break: the first line is the provocation, the rest is the next step.
    const [first, ...rest] = fillLink(draft.cta).split(/\n+/).filter(Boolean);
    children.push(new Paragraph({ children: [new TextRun({ text: first, bold: true })], spacing: { before: 160, after: 100 } }));
    for (const line of rest) children.push(new Paragraph({ text: line, spacing: { after: 140 } }));
  }
  if (draft.hashtags) {
    children.push(new Paragraph({ children: [new TextRun({ text: plain(draft.hashtags), color: BRAND_GREEN })], spacing: { after: 140 } }));
  }
  if (draft.image_ideas) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: "Image ideas: ", bold: true, color: GREY, size: 20 }),
          new TextRun({ text: plain(draft.image_ideas), color: GREY, size: 20 }),
        ],
        spacing: { before: 200 },
      }),
    );
  }

  return new Document({
    creator: "Phrenos.ai",
    title: plain(draft.title),
    sections: [{ ...brandedHeaderFooter("Blog", logo), children }],
  });
}

async function loadLogo(): Promise<Uint8Array | null> {
  try {
    const response = await fetch(LOGO_PATH);
    if (!response.ok) return null;
    return new Uint8Array(await response.arrayBuffer());
  } catch {
    return null;
  }
}

export function draftDocxFilename(draft: DraftForWord, isFullDraft: boolean) {
  const slug =
    (draft.title || "blog")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "phrenos-content";
  return `${slug}-blog-${isFullDraft ? "draft" : "idea"}.docx`;
}

/** Build the Word file in the browser and download it. */
export async function downloadDraftDocx(draft: DraftForWord, isFullDraft: boolean) {
  const logo = await loadLogo();
  const blob = await Packer.toBlob(buildDraftDocument(draft, isFullDraft, logo));
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = draftDocxFilename(draft, isFullDraft);
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
